### PR TITLE
Various fixes and improvements for input / label

### LINKED ISSUE #478: [1.0 Release Cleanup] Label
Breakout issue from https://github.com/Esri/calcite-components/issues/97

### Events
- [x] `calciteLabelSelectedEvent` - shouldn't be documented as it's only used by `calcite-input`. Focusing a wrapped `calcite-input` can potentially be handled in `focusChildEl` in `calcite-label`, and removed altogether in `calcite-label`.

### LINKED ISSUE #480: Allow removing margin above calcite-label
In a situation where having a margin above the input in not desired and there isn't a good way to remove it.

### LINKED ISSUE #581: [Research] Revisit click/focus behavior of <calcite-label> children
`<calcite-label>` has issues supporting focus behavior when wrapping `calcite-radio-button-group` due to the fact that `calcite-radio-button` renders a native `<input type="radio">` element for browser-default focus and keyboard behavior.

https://github.com/Esri/calcite-components/blob/master/src/components/calcite-label/calcite-label.tsx#L149-L151

☝️ We might want to revisit the need for this kind of behavior and/or consider modifying things to accommodate the `<input type="radio">` elements used by `calcite-radio-button` in order to allow this kind of focus behavior (if needed).

### LINKED ISSUE #593: [calcite-input] numeric properties should be typed as number
These props are currently typed [as string](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.tsx#L50-L56) and forces casting as string:

```tsx
render() {
  const [min, max] = dynamicallyComputeMinMax();

  // ...

  <calcite-input 
    max={max.toString(10)} 
    min={min.toString(10)} 
    ... />

  // ...
}
```

cc @macandcheese

### LINKED ISSUE #594: [calcite-input] Error is thrown when rendering calcite-input at the root level without wrapping element
The following toy snippet demonstrates an issue when there's no immediate wrapping element in a render method:

```tsx
render() {
  return <Host>
    <calcite-input type="text" placeholder="break!" />
  </Host>;
}
```

throws the following error:

```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.ael (index-b00ef87e.js:25)
    at index-b00ef87e.js:78
    at Array.map (<anonymous>)
    at addHostEventListeners (index-b00ef87e.js:74)
    at connectedCallback (index-b00ef87e.js:2011)
    at index-b00ef87e.js:2399
    at Object.jmp (index-b00ef87e.js:23)
    at HTMLElement.connectedCallback (index-b00ef87e.js:2399)
    at addVnodes (index-b00ef87e.js:779)
```

Wrapping it in an element works fine:

```tsx
render() {
  return <Host>
    <div>
      <calcite-input type="text" placeholder="break!" />
    </div>
  </Host>;
}
```

cc @macandcheese

### LINKED ISSUE #596: [calcite-input] calciteInputChange cannot be canceled
Similar to native `<input>` events, it would be useful to allow `calciteInputChange` to be canceled. This would require setting the `cancelable=true` option on [`@Event`]( https://stenciljs.com/docs/events#event-decorator) and updating the internal event handler.

cc @macandcheese

### LINKED ISSUE #627: Min & max properties as numbers on calcite-input?
The min & max properties on a numeric `calcite-input` are typed as string:

image

Is it because those properties can also be used on text inputs? If not and if there are only used for the "number" input, would it make sense for you to change their type to `number` as on the native number imput?

Thanks!

### LINKED ISSUE #667: [calcite-input] Add prop to disable component
Currently, there is no way to disable inputs without custom code. 

cc @macandcheese

### PR DESCRIPTION
**Pull request by macandcheese**
This is a catch-all for various requested fixes and improvements for input / label:

Biggest one is how we handle interaction with wrapped child elements:
- 🚨 - `calciteLabelSelectedEvent` event has been renamed to `calciteLabelFocus`
  - Instead of keeping logic for how to handle each possible child control inside `calcite-label`, emit a `calciteLabelFocus` event from `calcite-label` and listen for this in `calcite-switch/checkbox/radio-group/slider/etc.` and handle unique logic in the child control component (Resolves #581, Resolves #478)
   - I've tried to handle logic for the above existing controls, if you had worked on a component and want to handle this in a different way, go for it - I tried to explicitly request review from anyone who worked on one of the above. Everything *seems* to work and existing tests are passing but 🤷‍♂️...

- ➕ - Adds a `clearable` prop which, when requested, will show a clear button when a value is present - `clearable` also allows the `Escape` key to clear the value of the input (cc @nathan-barrett)
  - Search, Date, Time, get this updated clear button by default as they get a browser-rendered clear button otherwise
- ➕ - Adds `disabled` prop to input - element will be disabled and have 0.4 opacity styling (Resolves #667)
- ➕ - Adds a helper to determine if an element is contained within a label
- 🎨 - Removes top margin from `calcite-input` and instead displays only when `calcite-label` is used in a `default` full width alignment (Resolves #480)
- 🎨 - Standardizes heights of inputs, previously certain combinations of display options could cause inconsistencies
- 🎨 - No longer allows slotted actions to stretch the height of inputs
- 🎨 - Various fixes for style and alignment of inputs and wrapped controls
- ✔️ - Fix for inputs without direct parents incorrectly searching for props with closest() (Resolves #594)
- ✔️ - `calciteInputInput` is now cancellable (Resolves #596)
- ✔️ - Type min / max / step as number and transform to string as needed (Resolves #593, Resolves #627)
- 📓 - Updates dev demo examples, storybooks, tests

### CODE REVIEW

File: src/components/calcite-input/calcite-input.tsx [hunk 1]
```diff
@@ -166,14 +196,26 @@ export class CalciteInput {
...
+
+    this.determineClearable();
   }
 
   render() {
     const dir = getElementDir(this.el);
     const attributes = this.getAttributes();
+
+    const inputClearButton = (
+      <div
```
Comment (paulcpederson) [inline src/components/calcite-input/calcite-input.tsx:211]: I would wager that this is not accessible. Ie. in a screen-reader I would not even know about this element. This is apparently how the current browser-native clears are: 

> Of 9 browsers tested, six get a delete control and two of those also get a delete control on type="text". That means 4 of them get a delete control from type="search".
>
> Since screen readers do not announce this delete control (when it appears) and it can seemingly only be activated by pointer (I could not get it work in Voice Control), I don’t find it a compelling reason to use type="search". This does not even address target size, contrast, nor lack of accessible name.

—https://adrianroselli.com/2019/07/ignore-typesearch.html



Seems like if we make some tweaks we could substantially improve the screen reader experience for input fields, which is great.  We probably should use a button with `type=button`, allow devs to provide a label. Here's a discussion on ux stack exchange: https://ux.stackexchange.com/questions/125755/need-explanation-how-clear-input-button-accessibility-works

**Comment by paulcpederson** [comment]
Great improvements, @macandcheese ! Don't think the clear button is accessible, but neither are the browser defaults apparently... We could probably merge and open an issue and address later.

File: src/components/calcite-input/calcite-input.tsx (hunk 1 above)
Comment (macandcheese) [reply src/components/calcite-input/calcite-input.tsx:211]: Yeah that'd be a good improvement. Using "Escape" on a "clearable" input also works but to the point it's not announced that is a possible interaction anyway. 

Can update to use a button and accept a "clear button string" that is only used if "clearable" is requested as a prop (or, I guess, additionally for input types that would get a browser one by default - search, time, date).

File: src/components/calcite-checkbox/calcite-checkbox.scss [hunk 2]
```diff
@@ -1,15 +1,12 @@
...
   --calcite-checkbox-size: 12px;
-  top: 0.1em;
 }
 :host([scale="m"]) {
   --calcite-checkbox-size: 16px;
-  top: 0.15em;
 }
 :host([scale="l"]) {
   --calcite-checkbox-size: 20px;
-  top: 0.25em;
```
Comment (eriklharper) [inline src/components/calcite-checkbox/calcite-checkbox.scss:12]: Ooh this is nice, this will help on the new `calcite-tile-select` component I'm working on.  Noticed its position being slightly off because of these `top` values.

**Comment by macandcheese** [comment]
Merging - @paulcpederson I'll open an issue to track clear button updates.
