### PR TITLE
fix(button): Allow slotted button content without text

### LINKED ISSUE #1438: Bug: calcite-button containing calcite-icon is blank at 1.0.0-beta.47
### Summary

The "X" icon is not appearing in a calcite-button at 1.0.0-beta.47; it does appear at 1.0.0-beta.46.

### Actual Behavior

image (in `div` with aliceblue background)

### Expected Behavior

image (in `div` with aliceblue background)

### Reproduction Steps

```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />

  <!-- blank -->
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.47/dist/calcite/calcite.css" />
  <script type="module" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.47/dist/calcite/calcite.esm.js"></script>

  <!-- OK -->
  <!--link rel="stylesheet" type="text/css" href="https://unpkg.com/@esri/calcite-components@1.0.0-beta.46/dist/calcite/calcite.css" />
  <script type="module" src="https://unpkg.com/@esri/calcite-components@1.0.0-beta.46/dist/calcite/calcite.esm.js"></script-->

</head>
<body style="padding:4px;">
  <div style="display: inline-block; background-color:aliceblue; width:32px; height:32px">
    <calcite-button appearance="transparent" color="dark" scale="s" width="auto">
      <calcite-icon scale="m" icon="x"></calcite-icon>
    </calcite-button>
  </div>
</body>
</html>
```

### Relevant Info 

Windows browsers Chrome 87, Firefox 84, Edge 87

### PR DESCRIPTION
**Pull request by macandcheese**
**Related Issue:** Resolves #1438 cc @MikeTschudi 

## Summary

This re-enables the ability to place things other than text content inside a button's slot.

Because of the way padding is applied to buttons, it means that users may need to manually constrain the height of buttons that contain slotted content other than text. This really shouldn’t be recommended, and the preferred method of adding icons should be icon-start / icon-end, but this change will allow certain unique cases to be achieved. cc @asangma cc @MikeTschudi 

It should be noted Safari can't really handle "user set height and width" like in the added demo. Not sure if @asangma has a neat trick for this, but since this is "non-recommended", I think we can let users handle positioning things inside the buttons with negative margin etc. if needed. I was unable to find a solution to this, it seems like a Safari-only issue (the three buttons in the screenshot's left are using user-set height / width, and custom content - svg or calcite-icon - whereas the fourth example uses icon-start as recommended and displays fine across browsers).

Slice

### CODE REVIEW

File: src/components/calcite-button/calcite-button.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ export class CalciteButton {
     );
 
     return (
-      <Host dir={dir} hasText={this.hasText}>
+      <Host dir={dir} hasContent={this.hasContent}>
```
Comment (eriklharper) [inline src/components/calcite-button/calcite-button.tsx:141]: Why not just set this prop to `reflect: true`?

**Review by eriklharper — APPROVED** [review]
👍

File: src/components/calcite-button/calcite-button.tsx (hunk 1 above)
Comment (driskull) [reply src/components/calcite-button/calcite-button.tsx:141]: I'm confused on why this is being set on the dom node? A css class should be used on an internal node instead of an invalid undeclared prop.

Comment (driskull) [reply src/components/calcite-button/calcite-button.tsx:141]: Can you add a css class on the `<Tag>`? Otherwise, an invalid prop is being exposed to the user.

**Review by driskull — CHANGES_REQUESTED** [review]

**Comment by macandcheese** [comment]
Ok, updated.. @asangma can you check to make sure this is still looking good 🕺  - I know there were a lot of css combos for the button alignment stuff that was added, I think this keeps them all in tact.

I also added a check for whitespace where it wouldn't be intended, for example -  on cards where line breaks existed between button tags in the html, that would now have unintentionally been interpreted as slotted content with this PR (as Screener picked up!).

File: src/components/calcite-button/calcite-button.tsx [hunk 2]
```diff
@@ -137,18 +137,21 @@ export class CalciteButton {
...
     );
 
+    const className = this.hasContent ? { ["class"]: CSS.contentSlotted } : null;
+
     return (
-      <Host dir={dir} hasText={this.hasText}>
+      <Host dir={dir}>
         <Tag
           {...attributes}
+          {...className}
```
Comment (driskull) [inline src/components/calcite-button/calcite-button.tsx:146]: Can you just do:

```
<Tag
class={{[CSS. contentSlotted]: this.hasContent}}
```

?

**Review by driskull — APPROVED** [review]
👍

**Review by eriklharper — APPROVED** [review]

File: src/components/calcite-button/calcite-button.tsx (hunk 2 above)
Comment (macandcheese) [reply src/components/calcite-button/calcite-button.tsx:146]: We could - it leaves an empty `class` attribute if `hasContent` is false though:
Screen Shot 2021-01-07 at 5 06 30 PM

Comment (driskull) [reply src/components/calcite-button/calcite-button.tsx:146]: what do you think @jcfranco? I think the empty class is ok but it's nitpicky.

**Comment by macandcheese** [comment]
@asangma could you check out this PR since it’s related to the content / alignment updates that were previously made? Thanks!

**Comment by julio8a** [comment]
@asangma, following up the review for this. ^

File: src/components/calcite-button/calcite-button.tsx (hunk 2 above)
Comment (paulcpederson) [reply src/components/calcite-button/calcite-button.tsx:146]: I think the stencil way to do this is:

```jsx
<Tag class={{ [CSS.contentSlotted]: this.hasContent }}>
```

ie. conditionally add the `CSS.contentSlotted` class if `this.hasContent` is true.

**Review by paulcpederson — APPROVED** [review]

**Comment by julio8a** [comment]
The last ping for @asangma, otherwise, let's move forward with this PR.

**Review by asangma — APPROVED** [review]
LGTM.

**Comment by julio8a** [comment]
Can we merge this? or is this something left?
