### PR TITLE
fix(input): Emit calciteInputInput on clear

### LINKED ISSUE #1065: Bug: calcite-input does not emit event when search input is cleared
### Actual Behavior
When you set calcite-input to `type="search"`, a clear input button appears on the right side when you add text into it. If you click the clear input button, the text is cleared but there is no `calciteInputInput` event emitted.

You can view the behavior in this codepen: https://codepen.io/noahmulfinger/pen/bGebBZO?editors=1010

### Expected Behavior

The input event should be emitted when you hit the clear input button.

### Reproduction Steps

1. In the codepen, type some text in the input. You will see the event value appended below the input.
2. Now hit the clear input button. No event will be emitted.

### PR DESCRIPTION
**Pull request by macandcheese**
Emits calciteInputInput on clear
Adds tests for clearing on key and clear button press

**Related Issue:**  Resolves #1065 cc @noahmulfinger

### CODE REVIEW

File: src/components/calcite-input/calcite-input.tsx [hunk 1]
```diff
@@ -446,6 +450,7 @@ export class CalciteInput {
 
   private clearInputValue = () => {
     this.value = "";
+    this.emitInputInput();
```
Comment (driskull) [inline src/components/calcite-input/calcite-input.tsx:453]: could you just `@Watch()` the `value` prop and then emit?

**Review by driskull — APPROVED** [review]
Looks good, with suggestion

**Review by paulcpederson — APPROVED** [review]

**Comment by paulcpederson** [comment]
Nice, tests as well! :100:

File: src/components/calcite-input/calcite-input.tsx (hunk 1 above)
Comment (driskull) [reply src/components/calcite-input/calcite-input.tsx:453]: This is emitted any time the value is cleared or typed. Is that all times `value` is modified? If so, then a `@Watch` makes sense.

**Comment by macandcheese** [comment]
@driskull I updated to emit the event via `@Watch` and added some tests around that for other instances where the value might change, aside from a user explicitly clearing via `Escape` key / clicking "X" button.

**Review by driskull — APPROVED** [review]
👍

**Comment by driskull** [comment]
Looks good!

File: src/components/calcite-input/calcite-input.tsx [hunk 2]
```diff
@@ -131,6 +131,13 @@ export class CalciteInput {
   /** input value */
   @Prop({ mutable: true, reflect: true }) value?: string = "";
 
+  @Watch("value") valueWatcher(): void {
+    this.calciteInputInput.emit({
+      element: this.childEl,
+      value: this.value
+    });
+  }
```
Comment (eriklharper) [inline src/components/calcite-input/calcite-input.tsx:139]: Have you checked to make sure this doesn't cause an infinite loop when the `value` prop is being controlled?  It looks like this is the only event that emits the new value, so if the developer is setting the `value` attribute directly as a result of this event being emitted, then the watcher will fire once when `this.value` first changes inside `inputInputHandler` and then when the event is emitted, this might fire again and again each time `value` is set from outside.

Comment (driskull) [reply src/components/calcite-input/calcite-input.tsx:139]: I think it should be ok because the watcher is only called if value is different. right?

Comment (eriklharper) [reply src/components/calcite-input/calcite-input.tsx:139]: Theoretically yes, but would be good to check just to rule out possible race conditions.  The reason I brought this up is that I had to remove an event emitter from a watch method in radio-button because it was causing just this kind of issue.

Comment (macandcheese) [reply src/components/calcite-input/calcite-input.tsx:139]: so would a check look like:

```
@Watch("value") valueWatcher(newValue: string, oldValue: string): void {
  if (newValue !== oldValue) {
    this.calciteInputInput.emit({
      element: this.childEl,
      value: this.value
    });
  }
}

```

Comment (eriklharper) [reply src/components/calcite-input/calcite-input.tsx:139]: Oh, by check I mean try and use calcite-input in a JSX app.  This watcher wouldn't fire unless the new value differs from the old, so this check wouldn't do any good.

Comment (macandcheese) [reply src/components/calcite-input/calcite-input.tsx:139]: Ah, ha. Yeah I thought that was the case with `@Watch`.

Comment (eriklharper) [reply src/components/calcite-input/calcite-input.tsx:139]: Yeah, my hunch/concern is that depending on how fast the user is typing, there could be a sync/timing issue with the value being set internally first and then broadcasted after, which then sets it again from the outside, potentially causing a mismatch.

If there does end up being an issue with this in production apps, we might be able to setup some kind of reusable pattern that we could implement with other similar components where we detect if the `value` attribute is being controlled, which would refrain from storing the value internally and just rely on the event emitter to broadcast the new value, which the app would then set each time it changed from the top down, just as react does with its one-way data flow.

If the value attribute is not controlled, then the current behavior would take place where `this.value` is updated on each change and the event is still emitted.  However, I found for many years that the controlled approach is far superior because it eliminates duplicate local state that can get out of sync with external app state, but it would still make sense to support such a use case since that is how the native input element behaves.
